print(type(True))
print(True)
print(False)
print("''''''''''''''''")
print("for and")
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print("''''''''''''''''")
print("for or")
print(True or True)
print(True or  False)
print(False or True)
print(False or False)